apiVersion: v1
kind: Pod
metadata:
  name: angular-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr-angular
      image: 2122609/angularimages:angularfirstcon
      ports:
        - containerPort: 8085